name: Godot Export

on: [push]

jobs:
  export-game:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.4

      # Ensure that you get the entire project history
      with:
        fetch-depth: 0

    - name: Godot Export
      uses: firebelley/godot-export@v2.8.1
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.3.3/Godot_v3.3.3-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.3.3/Godot_v3.3.3-stable_export_templates.tpz
        relative_project_path: ./godot/
        create_release: false

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
